version: "4"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/libpostgres/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=simple-notes

volumes:
  pgdata:
