openapi: 3.0.0
info:
  title: Simple Notes API
  version: 0.1.9

paths:
  /users:
    post:
      summary: Register a new user.
      tags:
        - users
      requestBody:
        $ref: "#/components/requestBodies/User"
      responses:
        "200":
          description: User has been created
  /session:
    post:
      summary: Logs in, and returns the authentication cookie
      tags:
        - session
      requestBody:
        $ref: "#/components/requestBodies/User"
      responses:
        "200":
          description: >
            Successfully authenticated.
            The session ID is returned in a cookie named `connect.sid`. You need to include this cookie in subsequent requests.
          headers:
            Set-Cookie:
              schema:
                type: string
    delete:
      summary: Logs the user out
      description: Deletes the current user session
      tags:
        - session
      responses:
        "200":
          description: OK

  /notes:
    get:
      summary: Get the user's notes
      tags:
        - notes
      security:
        - cookieAuth: []
      responses:
        "200":
          description: List of the user's notes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Note"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    post:
      summary: Create a new note
      tags:
        - notes
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NoteRequest"
      responses:
        "200":
          description: The newly created note
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Note"
        "401":
          $ref: "#/components/responses/UnauthorizedError"

  /notes/{noteId}:
    get:
      summary: Get a note
      tags:
        - notes
      security:
        - cookieAuth: []
      parameters:
        - $ref: "#/components/parameters/NoteId"
      responses:
        "200":
          description: The specified note
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Note"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    patch:
      summary: Update a note
      tags:
        - notes
      security:
        - cookieAuth: []
      parameters:
        - $ref: "#/components/parameters/NoteId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NoteRequest"
      responses:
        "200":
          description: The updated note
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Note"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    delete:
      summary: Delete a note
      tags:
        - notes
      security:
        - cookieAuth: []
      parameters:
        - $ref: "#/components/parameters/NoteId"
      responses:
        "200":
          description: Note was successfully deleted
        "401":
          $ref: "#/components/responses/UnauthorizedError"

tags:
  - name: users
    description: Everything about users
  - name: notes
    description: Everything about notes
  - name: session
    description: Handles cookie authentication

components:
  schemas:
    ObjectId:
      type: string
      format: ObjectId
      example: "610e9e9c6d14aa58ec37a62b"
      readOnly: true
    Note:
      type: object
      properties:
        title:
          type: string
          example: "ToDo List"
        content:
          type: string
          example: "- Do the dishes"
        userId:
          $ref: "#/components/schemas/ObjectId"
        _id:
          $ref: "#/components/schemas/ObjectId"
      required:
        - _id
        - userId
    NoteRequest:
      allOf:
        - $ref: "#/components/schemas/Note"
    User:
      type: object
      properties:
        email:
          type: string
          example: "johndoe@email.com"
          format: email
        password:
          type: string
          example: "password12345"
          format: password
          minLength: 6
          maxLength: 30
        _id:
          $ref: "#/components/schemas/ObjectId"
      required:
        - email
        - password
        - _id
  parameters:
    NoteId:
      in: path
      name: noteId
      schema:
        $ref: "#/components/schemas/ObjectId"
      required: true
      description: Numeric ID of the note to get
  requestBodies:
    User:
      required: true
      description: A JSON object containing user info
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/User"
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: connect.sid
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
